### ISSUE TITLE
Error Loading MarketPlace

### ISSUE THREAD

**Issue by Sobhika2** [Munett/piwik#1]
Hi,

I am getting an error while trying to access the MarketPlace in Piwik version 3.2.0. The error also appears while accessing the Administration tab. Attached is the error screens for the same.

The log displays below error messages:

[Fri Feb 16 12:41:52 2018] [error] [client 10.54.17.33] Error in Piwik: , referer: http://piwik-test.swissre.com/piwik/index.php?module=CoreAdminHome&action=home&idSite=1&period=day&date=yesterday&activated=

Can anybody help?

Regards
![administration](https://user-images.githubusercontent.com/26790315/36306603-8d8cfc30-133e-11e8-9f50-778ccd6db782.png)
![marketplace](https://user-images.githubusercontent.com/26790315/36306604-8da3c2da-133e-11e8-9ed3-de6ed178f925.png)

**Comment by acrogenesis** [comment]
This is not piwik repo the correct one to ask is https://github.com/matomo-org/matomo
